# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-14 13:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20170514_1237'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Restaurent',
            new_name='Restaurant',
        ),
        migrations.AlterField(
            model_name='food',
            name='category',
            field=models.CharField(choices=[('MF', 'Mexican Food'), ('IC', 'Italian Cuisine'), ('IF', 'Indian Food'), ('CF', 'Cajun Food'), ('SF', 'Soul Food'), ('TF', 'Thai Food'), ('GF', 'Greek Cuisine'), ('CHF', 'Chinese Food'), ('LC', 'Lebanese Cuisine'), ('JC', 'Japanese Cuisine'), ('AF', 'American Food'), ('MF', 'Moroccan Food'), ('MC', 'Mediterranean Cuisine'), ('FF', 'French Food'), ('SC', 'Spanish Cuisine'), ('GF', 'German Food'), ('KF', 'Korean Food'), ('VF', 'Vietnamese Food'), ('TC', 'Turkish Cuisine'), ('CRF', 'Caribbean Food')], max_length=3),
        ),
        migrations.AlterField(
            model_name='rating',
            name='average',
            field=models.FloatField(default=0.0),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
