# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-14 13:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20170514_1308'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food',
            old_name='restaurent',
            new_name='restaurant',
        ),
    ]
