# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-09 12:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_cart_cartitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompletedOrders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_items', models.CharField(max_length=500)),
                ('employee_id', models.PositiveIntegerField()),
                ('customer_id', models.PositiveIntegerField()),
                ('order_time', models.DateTimeField()),
                ('delivered_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('is_free', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='NewOrders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_items', models.CharField(max_length=500)),
                ('employee_id', models.PositiveIntegerField()),
                ('customer_id', models.PositiveIntegerField()),
                ('order_time', models.DateTimeField()),
            ],
        ),
    ]
