# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-09 12:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_delete_neworders'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewOrders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_items', models.CharField(max_length=500)),
                ('employee_id', models.PositiveIntegerField()),
                ('customer_id', models.PositiveIntegerField()),
                ('order_time', models.DateTimeField()),
                ('total_price', models.PositiveIntegerField()),
                ('address', models.CharField(max_length=300)),
            ],
        ),
    ]
