# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-09 12:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_neworders'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='neworders',
            name='address',
        ),
        migrations.RemoveField(
            model_name='neworders',
            name='customer_id',
        ),
        migrations.RemoveField(
            model_name='neworders',
            name='employee_id',
        ),
        migrations.RemoveField(
            model_name='neworders',
            name='order_time',
        ),
        migrations.RemoveField(
            model_name='neworders',
            name='total_price',
        ),
    ]
